### ISSUE TITLE
Outdated secret API URL for Rittmeier

### ISSUE THREAD

**Issue by Gira-X** [ironjan/MensaUPB#138]
I just wrote an email to Rittmeier@studentenwerk-pb.de, joyfully expecting my secret URL but got an automatic response instead:

```
Sehr geehrte Damen und Herren,

seit dem 1. Februar 2016 bin ich nicht mehr für das Studierendenwerk Paderborn tätig. Bitte wenden Sie sich mit ihrem Anliegen an <info@studentenwerk-pb.de>.  Ihre Nachricht wird nicht automatisch weitergeleitet.

Mit freundlichen Grüßen,

i.A. Florian Rittmeier
```

@ironjan Can info@studentenwerk-pb.de handle the secret URL or will this cause issues somewhere along the lines?

If it works, the README.md should be updated!

**Comment by ironjan** [comment]
Thanks for the info. I'll update the readme.

**Comment by ironjan** [comment]
You'll have to use the email address linked on http://www.studentenwerk-pb.de/gastronomie/rahmenbedingungen-fuer-speiseplan-nutzung/ to get a SECRET_URL
