### ISSUE TITLE
Menu teilen via Whatsapp, Facebook, etc

### ISSUE THREAD

**Issue by rejinka** [ironjan/MensaUPB#6]
Im Menü-Detailscreen sollte es die Möglichkeit geben, das Gericht zu teilen. Via:
- Google+
- Facebook
- Whatsapp
- Twitter
- etc

Verschickt wird dann ein einfacher Text wie zb "Heute gibt es in $Restaurant $Gericht"

**Comment by ironjan** [comment]
Probably won't implement.
