### ISSUE TITLE
Zuletzte ausgewählte Mensa speichern

### ISSUE THREAD

**Issue by cordlandwehr** [ironjan/MensaUPB#83]
Die App speichert nicht, welche Mensa zuletzt ausgewählt wurde, sodass man bei jedem Start neu die Mensa auswählen muss.
Gerade für dezentrale Mensen ist das aber interessant, da man bspw. nicht oft zwischen Hotspot und Mensa Akademia wechselt.

**Comment by ironjan** [comment]
Danke für den Hinweis. Werde das bei Gelegenheit umsetzen (nervt mich selber, habs aber immer vergessen zu notieren :D)

**Comment by ironjan** [comment]
Released on Beta (http://ironjan.de/mensaupb-beta/)
